name: CD
on:
  push:
		branches: [main]

jobs:
	build:
		runs-on: ubuntu-latest

		steps:
		- uses: actions/checkout@v2
		- uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm ci
    - run: npm run build
    - uses: JamesIves/github-pages-deploy-actions@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: out # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
